development:
  adapter: mysql
  database: knowledgemapper_development
  username: root
  password:
  socket: /tmp/mysql.sock
  
test:
  adapter: mysql
  database: knowledgemapper_test
  username: root
  password:
  socket: /tmp/mysql.sock